// LOOPS
// FOR
// WHILE 
// DO WHILE
// FOR OF
// FOR IN 


//FOR EACH
// MAP
// FILTER
// REDUCE



// for(i=1; i<10 ;  i++){
//     console.log(i)
//     console.log("hello- "+ i)
//     if(i%2==0){
//         i=i+1;
//     }else{
//         i=i+2
//     }
// }


//i=1 true output -- 1 hello 1       
// i =2 true  outpur 2 hello 2
// i= 4 true output  4 hello 4
// i= 8 true output  8 hello 8
// i = 16 false ---> terminate

// i=1

// while (i<11){
//     console.log("hello world- "+ i)
//   if(i%2==0){
//     i=i+2;
//   }else{
//     i=i+3;
//   }
// }


// i=10;

// do{
//     console.log("heloo "+ i)
//     i++;

// }while(i<10);

//     while(i<10){
//         console.log("hello "+ i)
//     }



